version: '3.4'

services:
  clinical_trial_metadata_web:
    image: ${DOCKER_REGISTRY-}clinical_trial_metadata_web
    container_name: clinical_trial_metadata_web
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - clinical_trial_metadata.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=clinical_trial_metadata.db;Database=clinicalTrialMetadata;Username=postgres;Password=${DB_PASSWORD}

  clinical_trial_metadata.db:
    image: postgres:13.2
    container_name: clinical_trial_metadata_db
    environment:
      - POSTGRES_DB=clinicalTrialMetadata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
